### ISSUE TITLE
Result of intersect() is a set, not a list

### ISSUE THREAD

**Issue by jpatokal** [karimbahgat/Pyqtree#12]
Per the API docs, `intersect()` returns a list; however, in reality, it returns a set.  This makes it impossible to store non-hashable types like dicts with `insert()`.

I [forked the repo](https://github.com/jpatokal/Pyqtree) and changed the set to a list, which otherwise works fine, but sometimes the list contains duplicates.  I presume the set is intended as a way to work around this, but why is this happening and would it be possible to fix at the source?

**Comment by chrisranderson** [comment]
Yeah I found it problematic too - I defined hash functions for my objects. I guess the lazy way might be `return list(set(results))`.

**Comment by karimbahgat** [comment]
Seems like a common scenario I guess. Merged your fork @jpatokal in #14. Tried solving the duplicate problem in the way that @chrisranderson suggested, but calling `set()` means that the non-hashable objects will still fail. Solved instead via a manual loop and testing for list containment. The reason there are duplicates, may be that an item can span multiple sub-quads or exist right on the border. So non-hashables should work now.

**Comment by chrisranderson** [comment]
Haha whoops that's embarrassing. Only problem now is that checking for list containment is potentially really slow for large lists, right?

**Comment by karimbahgat** [comment]
You're right. At first I thought it would be managable, but when I ran benchmark.py on an index with 10,000 items, which before completed in 0.0 seconds, it now took 19 seconds! Currently it's implemented like this:

        uniq = []
        for item in self._intersect(bbox):
            if item not in uniq:
                uniq.append(item)
        return uniq

Maybe creating a temporary set() of id() values, and then doing list containment on that (which should be faster)? Only thing is all those id() calls may be quite slow too.. Any other suggestions?

**Comment by karimbahgat** [comment]
The benchmark includes items with random spans and thus widespread overlaps between items and across quads, and the query was for a relatively large area. For one test, the list results were ca 6000 and set results ca 1000 (ca 5000 duplicates and lots of containment tests).

**Comment by karimbahgat** [comment]
Tested the set() of id() idea, and it only slowed it down from the original 0.01 secs, to ca 0.05, which is much much better and absolutely acceptable. Going for that for now.

**Comment by karimbahgat** [comment]
I tested that hashable types are now supported, @jpatokal and @chrisranderson can you test on your use-cases and see how it goes?

**Comment by karimbahgat** [comment]
Fixed in new pypi release 1.0.0.
