### ISSUE TITLE
Updating coordinates

### ISSUE THREAD

**Issue by kalsan** [karimbahgat/Pyqtree#15]
Pardon my ignorance, I'm completely new to spacial indexing. I'm looking for a framework that allows to update an index (e.g. "Update object A with previous coordinates (x0,y0) for new position (x1,y1)"). 

Pyqtree allows to remove the element and re-add it, but there is no update operation. Is this the state-of-the-art way to do it or does that mean that Pyqtree was not intended for this particular use case?

Your answer will enlarge my horizon, thank you very much in advance.

**Comment by amras0000** [comment]
changing the index of an existing item would require finding a new quad for it, inserting it there, then cleaning up any empty quads it left behind. From an internal perspective, this would be equivalent (and probably implemented as) removing the item, then re-adding it.

**Comment by kalsan** [comment]
Thanks for your reply! Very helpful
