### ISSUE TITLE
insert data not in bbox object?

### ISSUE THREAD

**Issue by sophieclayton** [karimbahgat/Pyqtree#4]
I'd like to use data that is already on a regular grid, so I already have a dataframe with ((xmin, ymin, xmax, ymax)) for each of my items... Is it possible to populate the index with the data in this form rather than a bbox object?

E.g., I have a dataframe with columns ['data', 'xmin', 'xmax', 'ymin', 'ymax']
Is there a way to add each row of the dataframe to the index without the extra step of creating a bbox object?

**Comment by karimbahgat** [comment]
Hi, i almost forgot about this. If i understand you correctly, you are looping through the rows of a dataframe/table that has the bbox corners stored as four separate row values. Theres no need for a special method to handle that. The bbox argument to the insert() method is just an ordinary list or tuple. So all you need is to retrieve each of the corner values into a tuple or list and then pass that on to the insert() method. Unless i misunderstood you?

**Comment by karimbahgat** [comment]
So basically, there is no bbox class or object, its just a tuple or list and has no noticable overhead at all, nothing more than the cost of assigning any other python variable. So not sure why you want to skip that step.
