### ISSUE TITLE
Why do not delete a node operation?

### ISSUE THREAD

**Issue by LashengRamsey** [karimbahgat/Pyqtree#8]
Why do not delete a node operation?

**Comment by karimbahgat** [comment]
I don't understand this question, could you elaborate?

**Comment by de-code** [comment]
I imagine the question is why there isn't an operation to delete a node (at least that is a question that would be on my mind).

**Comment by karimbahgat** [comment]
Aha, makes more sense now. Good question, I guess it would be useful to allow that. Only thing is this im not fully sure if removing an item also requires removing node/rebuilding parts of the tree.. I don't currently have the time, but would welcome PRs from anyone who knows how.

**Comment by de-code** [comment]
If I submitted a PR, is it okay to remove the .pyc file (and add it to git ignore), or was that added intentionally?

**Comment by de-code** [comment]
You have a PR now.

**Comment by karimbahgat** [comment]
PRs are much appreciated! Removing the .pyc file is fine, i had just forgotten to do it.
